from typing import List
from .base import BaseFormatter
from ..instruction import InstructionInfo


class RuleFormatter(BaseFormatter):
    """Format as complete YARA rule"""

    def format(self, instructions: List[InstructionInfo], arch_name: str) -> str:
        if not instructions:
            return ""

        opcodes = [inst.formatted_hex() for inst in instructions]

        # Join with spaces for YARA format
        hex_pattern = " ".join(opcodes)

        # Create rule name based on function if available
        rule_name = "binary_ninja_export"
        if instructions and hasattr(instructions[0], "function_name"):
            rule_name = f"func_{instructions[0].function_name}"

        # Build complete YARA rule
        result = f"""rule {rule_name} {{
    meta:
        description = "Auto generated by Binary Ninja YARA plugin"
        architecture = "{arch_name}"
        
    strings:
        $bytes = {{ {hex_pattern} }}
        
    condition:
        $bytes
}}"""

        return result
